[2025-09-23T20:54:16.951+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-09-23T20:54:16.976+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: wine_pipeline.stage3_deploy_compose scheduled__2025-09-23T20:45:00+00:00 [queued]>
[2025-09-23T20:54:16.985+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: wine_pipeline.stage3_deploy_compose scheduled__2025-09-23T20:45:00+00:00 [queued]>
[2025-09-23T20:54:16.985+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 4
[2025-09-23T20:54:16.999+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): stage3_deploy_compose> on 2025-09-23 20:45:00+00:00
[2025-09-23T20:54:17.007+0000] {standard_task_runner.py:72} INFO - Started process 685 to run task
[2025-09-23T20:54:17.011+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'wine_pipeline', 'stage3_deploy_compose', 'scheduled__2025-09-23T20:45:00+00:00', '--job-id', '250', '--raw', '--subdir', 'DAGS_FOLDER/wine_pipeline.py', '--cfg-path', '/tmp/tmpkxn2_lyg']
[2025-09-23T20:54:17.015+0000] {standard_task_runner.py:105} INFO - Job 250: Subtask stage3_deploy_compose
[2025-09-23T20:54:17.089+0000] {task_command.py:467} INFO - Running <TaskInstance: wine_pipeline.stage3_deploy_compose scheduled__2025-09-23T20:45:00+00:00 [running]> on host a72da1fa20c9
[2025-09-23T20:54:17.207+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='wine_pipeline' AIRFLOW_CTX_TASK_ID='stage3_deploy_compose' AIRFLOW_CTX_EXECUTION_DATE='2025-09-23T20:45:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-09-23T20:45:00+00:00'
[2025-09-23T20:54:17.209+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-09-23T20:54:17.224+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-09-23T20:54:17.226+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'docker compose -f /opt/***/code/deployment/docker-compose.yml up -d --build']
[2025-09-23T20:54:17.240+0000] {subprocess.py:99} INFO - Output:
[2025-09-23T20:54:17.366+0000] {subprocess.py:106} INFO - time="2025-09-23T20:54:17Z" level=warning msg="/opt/***/code/deployment/docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion"
[2025-09-23T20:54:17.425+0000] {subprocess.py:106} INFO - time="2025-09-23T20:54:17Z" level=warning msg="Docker Compose is configured to build using Bake, but buildx isn't installed"
[2025-09-23T20:54:17.713+0000] {subprocess.py:106} INFO - #0 building with "default" instance using docker driver
[2025-09-23T20:54:17.714+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:17.715+0000] {subprocess.py:106} INFO - #1 [api internal] load build definition from Dockerfile
[2025-09-23T20:54:17.716+0000] {subprocess.py:106} INFO - #1 transferring dockerfile: 264B done
[2025-09-23T20:54:17.716+0000] {subprocess.py:106} INFO - #1 DONE 0.0s
[2025-09-23T20:54:17.717+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:17.718+0000] {subprocess.py:106} INFO - #2 [api internal] load metadata for docker.io/library/python:3.10-slim
[2025-09-23T20:54:18.274+0000] {subprocess.py:106} INFO - #2 DONE 0.7s
[2025-09-23T20:54:18.373+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.374+0000] {subprocess.py:106} INFO - #3 [api internal] load .dockerignore
[2025-09-23T20:54:18.375+0000] {subprocess.py:106} INFO - #3 transferring context: 2B done
[2025-09-23T20:54:18.376+0000] {subprocess.py:106} INFO - #3 DONE 0.0s
[2025-09-23T20:54:18.377+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.380+0000] {subprocess.py:106} INFO - #4 [api internal] load build context
[2025-09-23T20:54:18.381+0000] {subprocess.py:106} INFO - #4 transferring context: 64B done
[2025-09-23T20:54:18.382+0000] {subprocess.py:106} INFO - #4 DONE 0.0s
[2025-09-23T20:54:18.382+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.383+0000] {subprocess.py:106} INFO - #5 [api 1/5] FROM docker.io/library/python:3.10-slim@sha256:f8081b61393cc16b2339d377bb523a5646cdd28fc6105612b3893c405d27f730
[2025-09-23T20:54:18.384+0000] {subprocess.py:106} INFO - #5 resolve docker.io/library/python:3.10-slim@sha256:f8081b61393cc16b2339d377bb523a5646cdd28fc6105612b3893c405d27f730 0.0s done
[2025-09-23T20:54:18.385+0000] {subprocess.py:106} INFO - #5 DONE 0.0s
[2025-09-23T20:54:18.385+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.386+0000] {subprocess.py:106} INFO - #6 [api 2/5] WORKDIR /app
[2025-09-23T20:54:18.387+0000] {subprocess.py:106} INFO - #6 CACHED
[2025-09-23T20:54:18.388+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.389+0000] {subprocess.py:106} INFO - #7 [api 3/5] COPY requirements.txt .
[2025-09-23T20:54:18.390+0000] {subprocess.py:106} INFO - #7 CACHED
[2025-09-23T20:54:18.391+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.395+0000] {subprocess.py:106} INFO - #8 [api 4/5] RUN pip install --no-cache-dir -r requirements.txt
[2025-09-23T20:54:18.396+0000] {subprocess.py:106} INFO - #8 CACHED
[2025-09-23T20:54:18.397+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.397+0000] {subprocess.py:106} INFO - #9 [api 5/5] COPY main.py .
[2025-09-23T20:54:18.398+0000] {subprocess.py:106} INFO - #9 CACHED
[2025-09-23T20:54:18.400+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.401+0000] {subprocess.py:106} INFO - #10 [api] exporting to image
[2025-09-23T20:54:18.402+0000] {subprocess.py:106} INFO - #10 exporting layers done
[2025-09-23T20:54:18.403+0000] {subprocess.py:106} INFO - #10 exporting manifest sha256:1181bbbf188104c9b72cb7a4b2576a16324961a8a400b6cbb89476beb8892567 done
[2025-09-23T20:54:18.404+0000] {subprocess.py:106} INFO - #10 exporting config sha256:6aba02f92f2678889022da532e9cdcd4a3e3d2d98ebb364e58680ff23fa3269b done
[2025-09-23T20:54:18.405+0000] {subprocess.py:106} INFO - #10 exporting attestation manifest sha256:b06d4ed6802f297053066c3d7a9cfe1e51caa5da6ead6d05877cf86000e551dc
[2025-09-23T20:54:18.493+0000] {subprocess.py:106} INFO - #10 exporting attestation manifest sha256:b06d4ed6802f297053066c3d7a9cfe1e51caa5da6ead6d05877cf86000e551dc 0.0s done
[2025-09-23T20:54:18.495+0000] {subprocess.py:106} INFO - #10 exporting manifest list sha256:5e99bf456ddbf32bd997d0e5167c13caf33e37db175478332eccd48e7c2fdb70 0.0s done
[2025-09-23T20:54:18.497+0000] {subprocess.py:106} INFO - #10 naming to docker.io/library/wine-api:latest done
[2025-09-23T20:54:18.498+0000] {subprocess.py:106} INFO - #10 unpacking to docker.io/library/wine-api:latest 0.0s done
[2025-09-23T20:54:18.499+0000] {subprocess.py:106} INFO - #10 DONE 0.1s
[2025-09-23T20:54:18.634+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.636+0000] {subprocess.py:106} INFO - #11 [api] resolving provenance for metadata file
[2025-09-23T20:54:18.765+0000] {subprocess.py:106} INFO - #11 DONE 0.0s
[2025-09-23T20:54:18.949+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.950+0000] {subprocess.py:106} INFO - #12 [app internal] load build definition from Dockerfile
[2025-09-23T20:54:18.951+0000] {subprocess.py:106} INFO - #12 transferring dockerfile: 232B 0.0s done
[2025-09-23T20:54:18.951+0000] {subprocess.py:106} INFO - #12 DONE 0.0s
[2025-09-23T20:54:18.952+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:18.953+0000] {subprocess.py:106} INFO - #2 [app internal] load metadata for docker.io/library/python:3.10-slim
[2025-09-23T20:54:19.081+0000] {subprocess.py:106} INFO - #2 DONE 1.0s
[2025-09-23T20:54:19.216+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.226+0000] {subprocess.py:106} INFO - #13 [app internal] load .dockerignore
[2025-09-23T20:54:19.229+0000] {subprocess.py:106} INFO - #13 transferring context: 2B 0.0s done
[2025-09-23T20:54:19.231+0000] {subprocess.py:106} INFO - #13 DONE 0.0s
[2025-09-23T20:54:19.236+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.239+0000] {subprocess.py:106} INFO - #14 [app internal] load build context
[2025-09-23T20:54:19.243+0000] {subprocess.py:106} INFO - #14 transferring context: 63B 0.0s done
[2025-09-23T20:54:19.250+0000] {subprocess.py:106} INFO - #14 DONE 0.0s
[2025-09-23T20:54:19.254+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.255+0000] {subprocess.py:106} INFO - #5 [app 1/5] FROM docker.io/library/python:3.10-slim@sha256:f8081b61393cc16b2339d377bb523a5646cdd28fc6105612b3893c405d27f730
[2025-09-23T20:54:19.257+0000] {subprocess.py:106} INFO - #5 resolve docker.io/library/python:3.10-slim@sha256:f8081b61393cc16b2339d377bb523a5646cdd28fc6105612b3893c405d27f730 0.1s done
[2025-09-23T20:54:19.260+0000] {subprocess.py:106} INFO - #5 DONE 0.1s
[2025-09-23T20:54:19.320+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.321+0000] {subprocess.py:106} INFO - #6 [app 2/5] WORKDIR /app
[2025-09-23T20:54:19.324+0000] {subprocess.py:106} INFO - #6 CACHED
[2025-09-23T20:54:19.325+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.326+0000] {subprocess.py:106} INFO - #15 [app 3/5] COPY requirements.txt .
[2025-09-23T20:54:19.329+0000] {subprocess.py:106} INFO - #15 CACHED
[2025-09-23T20:54:19.331+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.332+0000] {subprocess.py:106} INFO - #16 [app 4/5] RUN pip install --no-cache-dir -r requirements.txt
[2025-09-23T20:54:19.333+0000] {subprocess.py:106} INFO - #16 CACHED
[2025-09-23T20:54:19.335+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.336+0000] {subprocess.py:106} INFO - #17 [app 5/5] COPY app.py .
[2025-09-23T20:54:19.338+0000] {subprocess.py:106} INFO - #17 CACHED
[2025-09-23T20:54:19.339+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.342+0000] {subprocess.py:106} INFO - #18 [app] exporting to image
[2025-09-23T20:54:19.344+0000] {subprocess.py:106} INFO - #18 exporting layers done
[2025-09-23T20:54:19.347+0000] {subprocess.py:106} INFO - #18 exporting manifest sha256:ed39c8a1281e8641f8221aa358161ed4a853cfca766b2391723ef213149408a1 done
[2025-09-23T20:54:19.349+0000] {subprocess.py:106} INFO - #18 exporting config sha256:6f0abffb2ffefdf85f78ba18149c8f66629e2f426c54fc38cab1a328af33f1f1 done
[2025-09-23T20:54:19.351+0000] {subprocess.py:106} INFO - #18 exporting attestation manifest sha256:344cae9289284f0c729110a9eefb6d4cd351bfff063d09f6aeff31f88c0ca73f 0.0s done
[2025-09-23T20:54:19.353+0000] {subprocess.py:106} INFO - #18 exporting manifest list sha256:95efe1ce9f21179b6b211e31513561d897a039c7d908f04558ca6d9b26420130
[2025-09-23T20:54:19.443+0000] {subprocess.py:106} INFO - #18 exporting manifest list sha256:95efe1ce9f21179b6b211e31513561d897a039c7d908f04558ca6d9b26420130 0.0s done
[2025-09-23T20:54:19.446+0000] {subprocess.py:106} INFO - #18 naming to docker.io/library/wine-app:latest done
[2025-09-23T20:54:19.447+0000] {subprocess.py:106} INFO - #18 unpacking to docker.io/library/wine-app:latest 0.0s done
[2025-09-23T20:54:19.449+0000] {subprocess.py:106} INFO - #18 DONE 0.2s
[2025-09-23T20:54:19.543+0000] {subprocess.py:106} INFO - 
[2025-09-23T20:54:19.544+0000] {subprocess.py:106} INFO - #19 [app] resolving provenance for metadata file
[2025-09-23T20:54:19.559+0000] {subprocess.py:106} INFO - #19 DONE 0.0s
[2025-09-23T20:54:19.560+0000] {subprocess.py:106} INFO -  api  Built
[2025-09-23T20:54:19.561+0000] {subprocess.py:106} INFO -  app  Built
[2025-09-23T20:54:19.583+0000] {subprocess.py:106} INFO -  Container wine-api-1  Recreate
[2025-09-23T20:54:19.849+0000] {subprocess.py:106} INFO -  Container wine-api-1  Recreated
[2025-09-23T20:54:19.853+0000] {subprocess.py:106} INFO -  Container wine-app-1  Recreate
[2025-09-23T20:54:20.266+0000] {subprocess.py:106} INFO -  Container wine-app-1  Recreated
[2025-09-23T20:54:20.316+0000] {subprocess.py:106} INFO -  Container wine-api-1  Starting
[2025-09-23T20:54:20.324+0000] {subprocess.py:106} INFO - Error response from daemon: mounts denied:
[2025-09-23T20:54:20.326+0000] {subprocess.py:106} INFO - The path /opt/***/models is not shared from the host and is not known to Docker.
[2025-09-23T20:54:20.328+0000] {subprocess.py:106} INFO - You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
[2025-09-23T20:54:20.330+0000] {subprocess.py:106} INFO - See https://docs.docker.com/go/mac-file-sharing/ for more info.
[2025-09-23T20:54:20.333+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-09-23T20:54:20.384+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/bash.py", line 232, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-23T20:54:20.405+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=wine_pipeline, task_id=stage3_deploy_compose, run_id=scheduled__2025-09-23T20:45:00+00:00, execution_date=20250923T204500, start_date=20250923T205416, end_date=20250923T205420
[2025-09-23T20:54:20.463+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-09-23T20:54:20.467+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 250 for task stage3_deploy_compose (Bash command failed. The command returned a non-zero exit code 1.; 685)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/providers/standard/operators/bash.py", line 232, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-09-23T20:54:20.524+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-09-23T20:54:20.556+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-09-23T20:54:20.558+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
